export const colors = {
    DarkBlue: '#24254A',
    Blue: '#21268F',
    LightBlue: '#21268F',
    Lavender: '#ECECF9',
    GhostWhite: '#F8F7FD',
    AzureishWhite: '#D7D8EF',
    LightPurpure: '#EBE0E9',
    TextColor: '#2D2E46',
    LightPink: '#D9D9F1',
    ActiveNavlinkColor: '#DCCCDB',
    BackgroundWight: '#FEFEFF',
    ToolsBackground: '#ECECF9',
    InputColor: '#635D80',
}